export const getUsers = async (req, res) => {
  try {
    //
  } catch (error) {
    console.error(error);
    return res.status(500).json({ message: 'failed to get users' });
  }
};

export const getUser = async (req, res) => {
  try {
    //
  } catch (error) {
    console.error(error);
    return res.status(500).json({ message: 'failed to get user' });
  }
};

export const updateUser = async (req, res) => {
  try {
    //
  } catch (error) {
    console.error(error);
    return res.status(500).json({ message: 'failed to update user' });
  }
};

export const deleteUser = async (req, res) => {
  try {
    //
  } catch (error) {
    console.error(error);
    return res.status(500).json({ message: 'failed to delete user' });
  }
};
